# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('being', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeingsEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_state', models.CharField(default='new', max_length=10, verbose_name='Prev state')),
                ('being', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='being_related', to='being.Being')),
            ],
            options={
                'verbose_name': 'Being event',
                'verbose_name_plural': 'Beings events',
            },
        ),
        migrations.CreateModel(
            name='BeingsListEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('POST', 'POST'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH')], max_length=10, verbose_name='State')),
            ],
            options={
                'verbose_name': 'Beings list event',
                'verbose_name_plural': 'Beings list events',
            },
        ),
    ]
